In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

model = Sequential([
      Dense(1, input_shape = (4,))
])

print(model.weights)

[<tf.Variable 'dense/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[0.0631609 ],
       [1.0447462 ],
       [0.8694556 ],
       [0.28567338]], dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]


In [ ]:
# (4, 1) input shape is length 4 i.e. we have total 4 records and dense layer has 1 unit. 
# Bias: (1,) bias has length 1. and bias value is 0. u can see from here numpy=array([0.]

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

my_var = tf.Variable([-1, 2])
print(my_var)

# it prints out the name, shape type and values of tensorflow variable
# we can change the types of variable by saying:

my_var = tf.Variable([-1, 2], dtype = tf.float32)
print(my_var)

# we can also give names to our variables 
my_var = tf.Variable([-1, 2], dtype = tf.float32, name = "my_var")
print(my_var)

# variable values are changed during training when we call "model.fit" operation. This will change the values for us as a part of optimization

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-1,  2], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([-1.,  2.], dtype=float32)>
<tf.Variable 'my_var:0' shape=(2,) dtype=float32, numpy=array([-1.,  2.], dtype=float32)>


### *we can also change varibale values manually. Every variable has assign method and we can always pass new values to store in variable.*
### remember the new assigned values should have the right shape 

In [ ]:
my_var= tf.Variable([-1, 2], dtype = tf.float32, name = "my_var")
my_var.assign([3.5, -1.])

# finally we can convert tf varibbles directly to numpy array. 
x = my_var.numpy()
print(x)

[ 3.5 -1. ]


Learning rate of the optimizer is also a variable. we might want to change the learning rate during training so we use variables for our custom work

**Useful Operations** 

In [ ]:
# create a constant tensor

t = tf.constant(np.array(80), shape = [5,2, 8])
t

<tf.Tensor: shape=(5, 2, 8), dtype=int64, numpy=
array([[[80, 80, 80, 80, 80, 80, 80, 80],
        [80, 80, 80, 80, 80, 80, 80, 80]],

       [[80, 80, 80, 80, 80, 80, 80, 80],
        [80, 80, 80, 80, 80, 80, 80, 80]],

       [[80, 80, 80, 80, 80, 80, 80, 80],
        [80, 80, 80, 80, 80, 80, 80, 80]],

       [[80, 80, 80, 80, 80, 80, 80, 80],
        [80, 80, 80, 80, 80, 80, 80, 80]],

       [[80, 80, 80, 80, 80, 80, 80, 80],
        [80, 80, 80, 80, 80, 80, 80, 80]]])>

In [ ]:
# Find rank of the matrix
rank = tf.rank(t)
print(rank)

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
# Reshape a tensor

t2 = tf.reshape(t, [8, 10])
t2

<tf.Tensor: shape=(8, 10), dtype=int64, numpy=
array([[80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80]])>

In [ ]:
print("t2 shape: ", t2.shape)

t2 shape:  (8, 10)


In [ ]:
ones = tf.ones(shape= (2, 3))
zeros = tf.zeros(shape= (2, 4))

eye = tf.eye(3) # used for identity matrix
tensor7 = tf.constant(7.0, shape=[2, 2])


In [ ]:
# Display the created tensors

print("\n Ones: \n ", ones)
print("\n zeros: \n ", zeros)
print("\n eye: \n ", eye)
print("\n tensor7: \n ", tensor7)


 Ones: 
  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)

 zeros: 
  tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)

 eye: 
  tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)

 tensor7: 
  tf.Tensor(
[[7. 7.]
 [7. 7.]], shape=(2, 2), dtype=float32)


In [ ]:
# Create two tensors

t1 = tf.zeros(shape= (2,2))
t2 = tf.ones(shape =(2, 2))
print(t1)
print(t2)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
# concatenate two tensors in any diretion

concat0 = tf.concat([t1, t2], 0)  # 0 mean vertically. 
print(concat0)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]], shape=(4, 2), dtype=float32)


In [ ]:
concat0 = tf.concat([t1, t2], 1)  # 1 mean Horizontally. 
print(concat0)

tf.Tensor(
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]], shape=(2, 4), dtype=float32)


In [ ]:
t = tf.constant(np.arange(24), shape = (3, 2, 4))
print("\n t shape: \n", t.shape)


 t shape: 
 (3, 2, 4)


In [ ]:
# Expanding the dimensions/rank of tensors
t1 = tf.expand_dims(t, 0)
t2 = tf.expand_dims(t, 1)
t3 = tf.expand_dims(t, 3)
# we r expanding our tensor at 3 different places

print("\n After expanding dims: \n t1 shape: ", t1.shape, "\n After expanding dims: \n t2 shape: ", t2.shape, "\n After expanding dims: \n t1 shape: ", t3.shape)


 After expanding dims: 
 t1 shape:  (1, 3, 2, 4) 
 After expanding dims: 
 t2 shape:  (3, 1, 2, 4) 
 After expanding dims: 
 t1 shape:  (3, 2, 4, 1)


In [ ]:
# squezing the redundant dimensions:

t1 = tf.squeeze(t1, 0)
print(t1.shape)
# this is used to retrieve original shape or dimensions of the matrix/tensor/vector
t2 = tf.squeeze(t2, 1)
print(t2.shape)

(3, 2, 4)
(3, 2, 4)


In [ ]:
# slicing a tensor
x = tf.constant([1,2,3,4,5,6,7])
print(x[1: -3])

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [ ]:
# Create a tensor with samples from a normal distribution

tn = tf.random.normal(shape = (2,2), mean = 0, stddev = 1.)
print(tn)

tf.Tensor(
[[-0.81997246 -1.0379481 ]
 [-0.28763196 -0.28084236]], shape=(2, 2), dtype=float32)


In [ ]:
# create a tensor with uniform distribution
tu = tf.random.uniform(shape = (2, 1), minval=0, maxval=10, dtype='int32')
tu

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[7],
       [0]], dtype=int32)>

In [ ]:
# create a tensor with poision distribution

tp = tf.random.poisson((2, 2), 5)
tp

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [9., 4.]], dtype=float32)>

In [ ]:
# more maths operation
d = tf.square(tn)
e = tf.exp(d)
f = tf.cos(e)

print(d)
print(e)
print(f)

tf.Tensor(
[[0.6723548  1.0773363 ]
 [0.08273214 0.07887243]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.9588447 2.9368463]
 [1.0862508 1.0820663]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.3783826  -0.97911257]
 [ 0.46580628  0.46950498]], shape=(2, 2), dtype=float32)
